In [9]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import stats

In [8]:
N = 10  # 데이터 갯수
K = 4   # 범주 갯수
mu_0 = np.ones(K) / K # np.ones : 모든 요소의 값이 1인 ndarray 만들기 -> 발생 확률
print(mu_0)

np.random.seed(42)
x = np.random.choice(K, N, p=mu_0) 

print(x)

c = np.bincount(x)
print(c)

print( stats.chisquare(c) )
print( stats.chisquare([7, 1, 1, 1]) )

[0.25 0.25 0.25 0.25]
[1 3 2 2 0 0 0 3 2 2]
[3 1 4 2]
Power_divergenceResult(statistic=np.float64(2.0), pvalue=np.float64(0.5724067044708798))
Power_divergenceResult(statistic=np.float64(10.8), pvalue=np.float64(0.012858001156297613))


In [10]:
ad_df = pd.read_csv('data-files/ad.csv')
ad_df

광고      구입
0    B  하지 않았다
1    B  하지 않았다
2    A      했다
3    A      했다
4    B  하지 않았다
..  ..     ...
995  B  하지 않았다
996  B  하지 않았다
997  B  하지 않았다
998  B  하지 않았다
999  A      했다

[1000 rows x 2 columns]

In [ ]:
# ad_stats = ad_df.groupby('광고')["구입"].count().reset_index() # 전체 갯수
ad_stats = ad_df.groupby('광고')["구입"].value_counts().reset_index() # 값 별 갯수
ad_stats

광고      구입  count
0  A  하지 않았다    351
1  A      했다     49
2  B  하지 않았다    549
3  B      했다     51

In [21]:
print( ad_stats.iloc[1, 2] / ad_stats.iloc[:2, 2].sum() ) # A 광고 구매율
print( ad_stats.iloc[3, 2] / ad_stats.iloc[2:, 2].sum() ) # B 광고 구매율

0.1225
0.085


In [25]:
# 교차표 작성
ad_cross1 = ad_stats.pivot_table(index="광고", columns="구입", values="count")
ad_cross2 = pd.crosstab(ad_df['광고'], ad_df["구입"])

In [27]:
# chi-square test
# stats.chi2_contingency(ad_cross1)
stats.chi2_contingency(ad_cross2)

Chi2ContingencyResult(statistic=np.float64(3.344907407407407), pvalue=np.float64(0.06741327136707487), dof=1, expected_freq=array([[360.,  40.],
       [540.,  60.]]))