In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import stats

In [15]:
N = 10  # 데이터 갯수
K = 4   # 범주 갯수
mu_0 = np.ones(K) / K # np.ones : 모든 요소의 값이 1인 ndarray 만들기 -> 발생 확률
print(mu_0)

np.random.seed(42)
x = np.random.choice(K, N, p=mu_0) 

print(x)

c = np.bincount(x)
print(c)

print( stats.chisquare(c) )
print( stats.chisquare([9, 0, 0, 1]) )

[0.25 0.25 0.25 0.25]
[1 3 2 2 0 0 0 3 2 2]
[3 1 4 2]
Power_divergenceResult(statistic=np.float64(2.0), pvalue=np.float64(0.5724067044708798))
Power_divergenceResult(statistic=np.float64(22.799999999999997), pvalue=np.float64(4.445073647060652e-05))
