In [25]:
import numpy as np
import pandas as pd

In [26]:
df2 = pd.DataFrame([
    ['green', 'M', 10.1, 'class1'],
    ['red', 'L', 13.5, 'class2'],
    ['blue', 'XL', 15.3, 'class1'],
])
df2.columns = ['color', 'size', 'price', 'classlabel']
df2

color size  price classlabel
0  green    M   10.1     class1
1    red    L   13.5     class2
2   blue   XL   15.3     class1

In [27]:
# np.unique(df2['classlabel'], return_counts=True)
# df2['classlabel'].unique()

# class_mapping = { 'class1' : 0, 'class2' : 1, 'class3' : 2} # 순위형 범주 데이터
class_mapping = {
    label : idx for idx, label in enumerate(np.unique(df2['classlabel']))
}
class_mapping
df2['classlabel2'] = df2['classlabel'].map(class_mapping)
df2

color size  price classlabel  classlabel2
0  green    M   10.1     class1            0
1    red    L   13.5     class2            1
2   blue   XL   15.3     class1            0

In [28]:
inv_class_mapping = { v : k for k, v in class_mapping.items() }
print(inv_class_mapping)
df2['classlabel2'] = df2['classlabel2'].map(inv_class_mapping)
df2

{0: 'class1', 1: 'class2'}


color size  price classlabel classlabel2
0  green    M   10.1     class1      class1
1    red    L   13.5     class2      class2
2   blue   XL   15.3     class1      class1

In [29]:
df2

color size  price classlabel classlabel2
0  green    M   10.1     class1      class1
1    red    L   13.5     class2      class2
2   blue   XL   15.3     class1      class1

In [ ]:
from sklearn.preprocessing import LabelEncoder # 범주형 -> 순위형 변경 도구

class_le = LabelEncoder()
print(df2['classlabel'].values)
# y = class_le.fit_transform(df2['classlabel'].values) # fit + transform
class_le.fit(df2['classlabel'].values)
y = class_le.transform(df2['classlabel'].values)
y


['class1' 'class2' 'class1']


array([0, 1, 0])

In [32]:
df2['classlabel'] = class_le.fit_transform(df2['classlabel'].values)
df2

color size  price  classlabel classlabel2
0  green    M   10.1           0      class1
1    red    L   13.5           1      class2
2   blue   XL   15.3           0      class1

In [34]:
# class_le.inverse_transform(df2['classlabel'].values)

df2['classlabel'] = class_le.inverse_transform(df2['classlabel'].values)
df2

color size  price classlabel classlabel2
0  green    M   10.1     class1      class1
1    red    L   13.5     class2      class2
2   blue   XL   15.3     class1      class1

In [35]:
from sklearn.preprocessing import OneHotEncoder

In [36]:
X = df2[['color', 'price']].values
X


array([['green', 10.1],
       ['red', 13.5],
       ['blue', 15.3]], dtype=object)

In [37]:
color_le = LabelEncoder()
X[:, 0] = color_le.fit_transform(X[:, 0])
X


array([[1, 10.1],
       [2, 13.5],
       [0, 15.3]], dtype=object)

In [43]:
ohe = OneHotEncoder()
encoded = ohe.fit_transform(X[:, [0]]).toarray()
encoded

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [44]:
pd.get_dummies(df2[['price', 'color']])

price  color_blue  color_green  color_red
0   10.1       False         True      False
1   13.5       False        False       True
2   15.3        True        False      False

In [49]:
df_wine = pd.read_csv('data-files/winequality-white.csv',sep=";")
df_wine.head(3)

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.0              0.27         0.36            20.7      0.045   
1            6.3              0.30         0.34             1.6      0.049   
2            8.1              0.28         0.40             6.9      0.050   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 45.0                 170.0   1.0010  3.00       0.45   
1                 14.0                 132.0   0.9940  3.30       0.49   
2                 30.0                  97.0   0.9951  3.26       0.44   

   alcohol  quality  
0      8.8        6  
1      9.5        6  
2     10.1        6

In [50]:
df_wine.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

In [61]:
from sklearn.model_selection import train_test_split

X, y = df_wine.iloc[:, :-1].values, df_wine.iloc[:, -1].values

# X_train, X_test, y_train, y_test = \
#     train_test_split(X, y, test_size=0.3, random_state=42)

X_train, X_test, y_train, y_test = \
     train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)
    
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((3428, 11), (1470, 11), (3428,), (1470,))

In [52]:
np.unique(y, return_counts=True)

(array([3, 4, 5, 6, 7, 8, 9]),
 array([  20,  163, 1457, 2198,  880,  175,    5]))

In [62]:
np.unique(y_test, return_counts=True)

(array([3, 4, 5, 6, 7, 8, 9]), array([  6,  49, 437, 660, 264,  53,   1]))