In [3]:
import numpy as np

In [6]:
l = [1, 2, 3, 4, 5]
l2 = np.array(l)
l3 = np.array(l, dtype='float32')

print( type(l), type(l2) )
print( type(l[0]), type(l2[0]), type(l3[0]))

<class 'list'> <class 'numpy.ndarray'>
<class 'int'> <class 'numpy.int64'> <class 'numpy.float32'>


In [9]:
a = np.array([[1,2,3],[4,5,6]])
print (a.shape) 
print(a)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [8]:
a.shape = (3, 2)
print(a.shape)
print(a)

(3, 2)
[[1 2]
 [3 4]
 [5 6]]


In [12]:
a = np.arange(24) # range(24)
print(a.ndim)
print(a)
b = a.reshape(2,4,3)
print(b.ndim)
print(b)


1
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
3
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [18]:
x = np.empty([3,2], dtype=int)
print(x)
x = np.zeros((5,), dtype="int")
print(x)
x = np.ones([2,2], dtype=int)
print(x)


[[1 2]
 [3 4]
 [5 6]]
[0 0 0 0 0]
[[1 1]
 [1 1]]


In [21]:
x = np.arange(10, 20, 2) # from, to, step
print (x)


[10 12 14 16 18]


In [23]:
a = np.linspace(1.0, 2.0, num = 5)
print (a)

x = np.linspace(10, 20, 5, endpoint = False)
print (x)



[1.   1.25 1.5  1.75 2.  ]
[10. 12. 14. 16. 18.]


In [25]:
a = np.arange(10)
b = a[2:7:2] # [from:to:step]
print (b)

[2 4 6]


In [26]:
a = np.arange(10)
b = a[5]
print (b)


5


In [27]:
a = np.arange(10)
print (a[2:]) 

[2 3 4 5 6 7 8 9]


In [29]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]])
print (a)
print (a.shape)
print (a[1:])


[[1 2 3]
 [3 4 5]
 [4 5 6]]
(3, 3)
[[3 4 5]
 [4 5 6]]


In [30]:
x = np.array([[1, 2], [3, 4], [5, 6]])
y = x[[0,1,2], [0,1,0]]
print (y)


[1 4 5]


In [31]:
x = np.array([[ 0, 1, 2],[ 3, 4, 5],[ 6, 7, 8],[ 9, 10, 11]])
print(x)
z = x[1:4,1:3] # 1 ~ 4행, 1 ~ 3열
print (z)
y = x[1:4,[1,2]]
print (y)


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 4  5]
 [ 7  8]
 [10 11]]
[[ 4  5]
 [ 7  8]
 [10 11]]


In [33]:
x = np.array([[ 0, 1, 2],[ 3, 4, 5],[ 6, 7, 8],[ 9, 10, 11]])
print(x > 5)
print(x[x > 5])

[[False False False]
 [False False False]
 [ True  True  True]
 [ True  True  True]]
[ 6  7  8  9 10 11]


In [35]:
a = np.array([np.nan, 1, 2, np.nan, 3, 4, 5])
print(np.isnan(a))
print(~np.isnan(a))
print(a[~np.isnan(a)])


[ True False False  True False False False]
[False  True  True False  True  True  True]
[1. 2. 3. 4. 5.]


In [36]:
a = np.array([1,2,3,4])
b = np.array([10,20,30,40])
c = a * b
print(c)


[ 10  40  90 160]


In [41]:
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]])
b = np.array([1.0,2.0,3.0])
print(a.shape, b.shape)
print (a + b)

(4, 3) (3,)
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


In [42]:
a = np.arange(0,60,5)
a = a.reshape(3,4)
print(a)
for x in np.nditer(a, order = 'C'):
    print (x, end=' ')
print ('\n')
for x in np.nditer(a, order = 'F'):
    print (x, end=' ')


[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
0 5 10 15 20 25 30 35 40 45 50 55 

0 20 40 5 25 45 10 30 50 15 35 55 