In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.datasets import load_iris

In [3]:
iris_dataset = load_iris()

In [ ]:
# scikit-learn이 제공하는 데이터셋의 구조 확인
print( type(iris_dataset) ) # iris_dataset 은 dict와 유사한 구조
print( iris_dataset.keys() )
# print( iris_dataset['DESCR'] )
print( iris_dataset['data'][:3, :] )        # feature(X)에 해당하는 데이터 
print( iris_dataset['target'][:3] )         # target(y)에 해당하는 데이터
print( np.unique(iris_dataset['target']) )  # target(y)에 해당하는 데이터
print( iris_dataset['target_names'] )       # target(y)의 실제 값

<class 'sklearn.utils._bunch.Bunch'>
dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]]
[0 0 0]
[0 1 2]
['setosa' 'versicolor' 'virginica']


In [13]:
def net_input(X, w): # X : 1D array, w : 1D array
    # return sum([x*w for x, w in zip(X, w[1:])]) + w[0]
    return np.dot(X, w[1:]) + w[0] # w1*x1 + w2*x2 + ... wn*xn + w0*1

In [15]:
net_input([1, 2, 3, 4, 5], [10, 20, 30, 40, 50, 60])

np.int64(710)

In [16]:
def activation(v):
    # if v > 0:
    #     return 1
    # else:
    #     return -1
    return 1 if v > 0 else -1

In [19]:
activation(0.7), activation(-0.2)

(1, -1)

In [20]:
def predict(X, w):
    net_value = net_input(X, w)
    activated_value = activation(net_value)
    return activated_value