In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
# 파일에서 데이터 읽기
from sklearn.datasets import load_files # 여러 개의 파일에서 데이터를 읽는 도구

reviews_train = load_files('data-files/aclImdb/train')
reviews_test = load_files('data-files/aclImdb/test')

In [ ]:
# 데이터 기본 정보 탐색
print( reviews_train.keys() )
print( len( reviews_train['data'] ), len( reviews_test['data'] ) )
print( np.unique(reviews_train['target'], return_counts=True) )
print( reviews_train['target_names'])
print( reviews_train['data'][0])

dict_keys(['data', 'filenames', 'target_names', 'target', 'DESCR'])
25000 25000
(array([0, 1]), array([12500, 12500]))
['neg', 'pos']
b"Zero Day leads you to think, even re-think why two boys/young men would do what they did - commit mutual suicide via slaughtering their classmates. It captures what must be beyond a bizarre mode of being for two humans who have decided to withdraw from common civility in order to define their own/mutual world via coupled destruction.<br /><br />It is not a perfect movie but given what money/time the filmmaker and actors had - it is a remarkable product. In terms of explaining the motives and actions of the two young suicide/murderers it is better than 'Elephant' - in terms of being a film that gets under our 'rationalistic' skin it is a far, far better film than almost anything you are likely to see. <br /><br />Flawed but honest with a terrible honesty."


In [8]:
# 효과적인 전처리를 위해 DataFrame으로 변환
reviews_train_df = pd.DataFrame({'label': reviews_train['target'], 
                                 'review' : reviews_train['data']})
reviews_test_df = pd.DataFrame({'label': reviews_test['target'], 
                                'review' : reviews_test['data']})

In [9]:
# 데이터 프레임 확인
reviews_train_df.head()

label                                             review
0      1  b"Zero Day leads you to think, even re-think w...
1      0  b'Words can\'t describe how bad this movie is....
2      1  b'Everyone plays their part pretty well in thi...
3      0  b'There are a lot of highly talented filmmaker...
4      0  b'I\'ve just had the evidence that confirmed m...

In [11]:
# binary text -> char text
reviews_train_df['review'] = reviews_train_df['review'].str.decode(encoding='utf-8')
reviews_test_df['review'] = reviews_test_df['review'].str.decode(encoding='utf-8')

In [12]:
# decode 확인
reviews_train_df.head()

label                                             review
0      1  Zero Day leads you to think, even re-think why...
1      0  Words can't describe how bad this movie is. I ...
2      1  Everyone plays their part pretty well in this ...
3      0  There are a lot of highly talented filmmakers/...
4      0  I've just had the evidence that confirmed my s...

In [13]:
# 처리된 데이터 파일로 저장 ( 개별 파일에서 읽기 속도가 느려서 별도 파일로 저장 )
reviews_train_df.to_csv('data-files/imdb_reviews_train.csv', index=False)
reviews_test_df.to_csv('data-files/imdb_reviews_test.csv', index=False)

In [14]:
# 저장된 파일 테스트
pd.read_csv('data-files/imdb_reviews_train.csv').head()

label                                             review
0      1  Zero Day leads you to think, even re-think why...
1      0  Words can't describe how bad this movie is. I ...
2      1  Everyone plays their part pretty well in this ...
3      0  There are a lot of highly talented filmmakers/...
4      0  I've just had the evidence that confirmed my s...

In [16]:
# 데이터 정보 탐색 2
reviews_train_df.info()
reviews_test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   label   25000 non-null  int64 
 1   review  25000 non-null  object
dtypes: int64(1), object(1)
memory usage: 390.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   label   25000 non-null  int64 
 1   review  25000 non-null  object
dtypes: int64(1), object(1)
memory usage: 390.8+ KB


In [22]:
# 데이터 전처리 : 대문자 -> 소문자

reviews_train_df['review'] = reviews_train_df['review'].str.lower()
reviews_test_df['review'] = reviews_test_df['review'].str.lower()

In [23]:
# review에 markup(tag)가 포함된 것 확인 : <br />
reviews_train_df['review'][0]

"zero day leads you to think, even re-think why two boys/young men would do what they did - commit mutual suicide via slaughtering their classmates. it captures what must be beyond a bizarre mode of being for two humans who have decided to withdraw from common civility in order to define their own/mutual world via coupled destruction.<br /><br />it is not a perfect movie but given what money/time the filmmaker and actors had - it is a remarkable product. in terms of explaining the motives and actions of the two young suicide/murderers it is better than 'elephant' - in terms of being a film that gets under our 'rationalistic' skin it is a far, far better film than almost anything you are likely to see. <br /><br />flawed but honest with a terrible honesty."

In [25]:
# 데이터 전처리 2 : markup 제거
# reviews_train_df['review'] = reviews_train_df['review'].str.replace('<br />', '')

from bs4 import BeautifulSoup

# BeautifulSoup("<div>test</div>").get_text() # --> test만 추출
reviews_train_df['review'] = \
    reviews_train_df['review'].map(lambda v: BeautifulSoup(v, 'html.parser').get_text())
reviews_test_df['review'] = \
    reviews_test_df['review'].map(lambda v: BeautifulSoup(v, 'html.parser').get_text())

C:\Users\human\AppData\Local\Temp\ipykernel_4912\1110037150.py:8: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
  reviews_train_df['review'].map(lambda v: BeautifulSoup(v, 'html.parser').get_text())
C:\Users\human\AppData\Local\Temp\ipykernel_4912\1110037150.py:10: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
  reviews_test_df['review'].map(lambda v: BeautifulSoup(v, 'html.parser').get_text())


In [26]:
reviews_train_df['review'][0]

"zero day leads you to think, even re-think why two boys/young men would do what they did - commit mutual suicide via slaughtering their classmates. it captures what must be beyond a bizarre mode of being for two humans who have decided to withdraw from common civility in order to define their own/mutual world via coupled destruction.it is not a perfect movie but given what money/time the filmmaker and actors had - it is a remarkable product. in terms of explaining the motives and actions of the two young suicide/murderers it is better than 'elephant' - in terms of being a film that gets under our 'rationalistic' skin it is a far, far better film than almost anything you are likely to see. flawed but honest with a terrible honesty."

In [29]:
# 전처리 3 : 특수문자 제거 -> 영문자만 남겨두기 (정규표현식 사용)
import re

reviews_train_df['review'] = \
    reviews_train_df['review'].map(lambda v: re.sub('[^A-Za-z]', ' ', v))
reviews_test_df['review'] = \
    reviews_test_df['review'].map(lambda v: re.sub('[^A-Za-z]', ' ', v))

In [31]:
# 전처리 4 : 문장(single string) -> 단어(토큰) 리스트(string list)

import nltk # 자연어 처리를 위한 패키지

reviews_train_df['review'] = reviews_train_df['review'].map(nltk.word_tokenize)
reviews_test_df['review'] = reviews_test_df['review'].map(nltk.word_tokenize)

In [51]:
# 전처리 5 : 불용어(stopwords) 제거

# nltk.download('stopwords')
from nltk.corpus import stopwords

en_stopwords = stopwords.words('english') # english 불용어 사전 준비
print(en_stopwords[:10], len(en_stopwords))
# en_stopwords += ['test', 'xyz'] # 기존 stopwords에 새 단어 추가

# reviews_train_df['review'][:10].map(lambda v: [ t for t in v if t not in en_stopwords ] )

reviews_train_df['review'] = \
reviews_train_df['review'].map(lambda v: [ t for t in v if t not in en_stopwords ] )
reviews_test_df['review'] = \
reviews_test_df['review'].map(lambda v: [ t for t in v if t not in en_stopwords ] )


['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're"] 179


In [55]:
# 전처리 6 : 어근 추출 ( 단어 활용에 의해 철자가 달라진 단어를 표준화 또는 통합 )

from nltk import PorterStemmer

stemmer = PorterStemmer()
# print(stemmer.stem('happy'), stemmer.stem('apples'), stemmer.stem('apple'))

reviews_train_df['review'] = \
    reviews_train_df['review'].map(lambda v: [stemmer.stem(w) for w in v])
reviews_test_df['review'] = \
    reviews_test_df['review'].map(lambda v: [stemmer.stem(w) for w in v])

In [58]:
# 전처리 7 : 토큰 리스트(string list) -> 단일 문장 (single string)

# print( '$'.join(['abc', 'def', 'xyz', '123']) )

reviews_train_df['review'] = \
    reviews_train_df['review'].map(lambda v: ' '.join(v))
reviews_test_df['review'] = \
    reviews_test_df['review'].map(lambda v: ' '.join(v))

In [59]:
reviews_train_df['review'][0]

'zero day lead think even think two boy young men would commit mutual suicid via slaughter classmat captur must beyond bizarr mode two human decid withdraw common civil order defin mutual world via coupl destruct perfect movi given money time filmmak actor remark product term explain motiv action two young suicid murder better eleph term film get rationalist skin far far better film almost anyth like see flaw honest terribl honesti'

In [60]:
# 전처리 8 : string token -> numeric value

from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer()
sparse_train_counts = cv.fit_transform(reviews_train_df['review'])
sparse_test_counts = cv.transform(reviews_test_df['review']) # 테스트는 별도 훈련 없이 훈련 모델 사용

In [ ]:
# token -> number 변환기 확인
# print( sparse_train_counts )
print( "단어사전의 크기 : {0}".format(len( cv.vocabulary_.keys() ) ) )
idx_to_word = { idx: word for word, idx in cv.vocabulary_.items() }

단어사전의 크기 : 50573


In [71]:
idx_to_word[1234]

'amatuerish'

In [72]:
# 데이터 준비

X_train, y_train = sparse_train_counts, reviews_train_df['label']
X_test, y_test = sparse_test_counts, reviews_test_df['label']

In [78]:
# 모델 훈련 (학습)

from sklearn.linear_model import LogisticRegression

logreg = LogisticRegression(C=0.1, max_iter=10000, random_state=42)
logreg.fit(X_train, y_train)

logreg.score(X_train, y_train), logreg.score(X_test, y_test)

(0.96112, 0.87204)

In [80]:
print( reviews_train_df['review'][0] )
print( sparse_train_counts.toarray()[0])

zero day lead think even think two boy young men would commit mutual suicid via slaughter classmat captur must beyond bizarr mode two human decid withdraw common civil order defin mutual world via coupl destruct perfect movi given money time filmmak actor remark product term explain motiv action two young suicid murder better eleph term film get rationalist skin far far better film almost anyth like see flaw honest terribl honesti
[0 0 0 ... 0 0 0]


In [86]:
from sklearn.feature_extraction.text import TfidfTransformer, TfidfVectorizer

# tv = TfidfVectorizer() # raw string -> tfidf
# sparse_train_counts2 = tv.fit_transform(reviews_train_df['review'])
# sparse_test_counts2 = tv.transform(reviews_test_df['review'])

tt = TfidfTransformer() # int count data -> tfidf
sparse_train_counts2 = tt.fit_transform(sparse_test_counts)
sparse_test_counts2 = tt.transform(sparse_test_counts)

In [87]:
# 데이터 준비

X_train2, y_train2 = sparse_train_counts2, reviews_train_df['label']
X_test2, y_test2 = sparse_test_counts2, reviews_test_df['label']

In [88]:
# 모델 훈련 (학습)

from sklearn.linear_model import LogisticRegression

logreg2 = LogisticRegression(C=10, max_iter=10000, random_state=42)
logreg2.fit(X_train2, y_train2)

logreg2.score(X_train2, y_train2), logreg.score(X_test2, y_test2)

(0.97976, 0.85792)

In [94]:
type(reviews_test_df['review'])
reviews_test_df['review']

0        hate heather graham beauti hate fun watch movi...
1        know movi receiv mani posit comment one call a...
2        caught movi horror channel quit impress film g...
3        nbc chanc make power religi epic along line te...
4        look someth shock okay fine imageri film attem...
                               ...                        
24995    watch tip velvet sarah water decid watch finge...
24996    three main charact hopeless yet feel sorri one...
24997    review imdb documentari overr felt compel vent...
24998    forget said emeril rachael ray irrit person fo...
24999    could great film late poker pro pre poker craz...
Name: review, Length: 25000, dtype: object

In [ ]:
review = pd.Series(["""This movie reminds me of the value of family. 
I agree with my friend's comments.
This movie would be one of the best animated movies in my life, too."""])

transformed_review = cv.transform(review)

logreg.predict(transformed_review)

array([1])